[tools]
python = "3.12"
uv = 'latest'
prettier = 'latest'

# Automatic virtual environment
[env]
_.python.venv = { path = ".venv", create = true }
PROJECT_NAME = "{{ config_root | basename }}"
VIRTUAL_ENV = "{{ config_root }}/.venv"
PATH = "{{ config_root }}/.venv/bin:{{env.PATH}}"

[settings]
activate_aggressive = true

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Python: $(python --version)"
'''

[tasks.lint]
description = "Lint and check formatting with Ruff and Prettier"
run = "uv run ruff check . && uv run ruff format --check . && prettier --check ."

[tasks.format]
description = "Format and fix code with Ruff and Prettier"
run = "uv run ruff format . && uv run ruff check --fix . && prettier --write ."

# Tasks
[tasks.install]
description = "Install dependencies using uv"
run = "uv sync"

[tasks.new]
description = "Run the main script for 'new' entries"
run = "uv run -m selenium_notion_autofill new"
alias = ["n"]

[tasks.update]
description = "Run the main script for 'update-rejections' entries"
run = "uv run -m selenium_notion_autofill update-rejections"
alias = ["u"]

[tasks.add]
description = "Add a new dependency"
run = "uv add {args}"

[tasks.update-deps]
description = "Update dependencies"
run = "uv sync --upgrade"

[tasks.test]
description = "Run tests"
run = "uv run pytest"
